import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import background from "../public/background.jpg";
import axios from "axios";
import { BsSearch } from "react-icons/bs";
import Weather from "../Components/Weather";
import Spinner from "../Components/Spinner";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setloading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=dd828bab04c61ace60dfe4772b48ed87`;

  const fetchweather = (event) => {
    event.preventDefault();
    setloading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
    });
    setCity("");
    setloading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Image src={background} layout="fill" className=" object-cover" />

        <div className=" relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 z-10">
          <form className=" flex justify-between items-center w-full p-3 bg-transparent border border-gray-300 text-white rounded-2xl">
            <div>
              <input
                onSubmit={fetchweather}
                onChange={(event) => setCity(event.target.value)}
                className="w-full border-none text-white bg-transparent focus:outline-none text-2xl"
                type="text"
                placeholder="Search"
              />
            </div>
            <button onClick={fetchweather}>
              <BsSearch size={30} />
            </button>
          </form>
        </div>
        <div>{weather.main && <Weather data={weather} />}</div>
      </div>
    );
  }
}
